# Generated by Django 5.2 on 2025-04-27 10:22

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodoPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePago', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Metodos De Pago',
                'verbose_name_plural': 'Metodos de pagos',
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id_nosotros', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Nosotros',
                'verbose_name_plural': 'Nosotros',
                'db_table': 'nosotros',
            },
        ),
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Destino', models.CharField(max_length=150)),
                ('descripcion', models.TextField(default='descripcion')),
                ('image', models.URLField(blank=True)),
                ('precio_Destino', models.DecimalField(decimal_places=2, max_digits=12, validators=[accounts.models.positive_price_validator])),
                ('fecha_salida', models.DateTimeField()),
                ('cantidad_Disponible', models.IntegerField(default=12, validators=[accounts.models.positive_viaje_validator])),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='accounts.categorias')),
                ('id_metodoPago', models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='accounts.metodopago')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'destinos',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=3, validators=[accounts.models.positive_price_validator])),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_destino', models.ForeignKey(db_column='id_destino', on_delete=django.db.models.deletion.CASCADE, to='accounts.destinos')),
                ('id_metodoPago', models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='accounts.metodopago')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carrito',
                'db_table': 'carrito',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users/usuario_defecto.jpg', upload_to='users/', verbose_name='Imagen de perfil')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Localidad')),
                ('mail', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['-id'],
            },
        ),
    ]
